services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"
  app:
    build: .
    container_name: app
    volumes:
      - ./app:/app
    ports:
      - "8501:8501"
    depends_on:
      - ollama