services:

  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/db_data
    ports:
      - "5432:5432"
    networks:
      - local

  pgadmin:
    container_name: pgadmin
    image: elestio/pgadmin:REL-8_5
    restart: always
    env_file:
      - ./.env
    ports:
      - "5050:80"
    networks:
      - local

  keycloak:
    container_name: keycloak
    image: keycloak/keycloak:24.0
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    command: start-dev
    networks:
      - local


networks:
  local:

volumes:
  pg_data:
